version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGODB_URI} # or hardcode your Mongo URI here (not recommended)
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # maps nginx port 80 in container to localhost:3000
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge