spring:
  data:
    mongodb:
      uri: mongodb+srv://andrewjohnson9393:admin@cluster0.o1aj2hv.mongodb.net/FBJava

server:
  port: 3001

# Your secret key can be added here, but be careful with committing sensitive keys
secret:
  key: g92J!n7^f3Rb@Lp9#qvKzWxD!Tu6Vz*12Xe